### PR TITLE
Add AppVeyor manifest to test on Windows boxes.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by jfrazelle** [comment]
whoa this is fancy

On Wednesday, March 2, 2016, David Calavera <notifications@github.com>
wrote:

> Signed-off-by: David Calavera david.calavera@gmail.com
> <javascript:_e(%7B%7D,'cvml','david.calavera@gmail.com');>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/docker/engine-api/pull/125
> Commit Summary
>
>    - Add AppVeyor manifest to test on Windows boxes.
>
> File Changes
>
>    - *A* appveyor.yml
>    <https://github.com/docker/engine-api/pull/125/files#diff-0> (37)
>
> Patch Links:
>
>    - https://github.com/docker/engine-api/pull/125.patch
>    - https://github.com/docker/engine-api/pull/125.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/engine-api/pull/125>.
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by calavera** [comment]
@jfrazelle you should check the ones in https://github.com/docker/docker-credential-helpers, they even deploy binaries to GitHub releases :grin:

**Comment by calavera** [comment]
all :green_heart: :exclamation:

**Comment by jfrazelle** [comment]
ooooooo shinyyyyy

On Wed, Mar 2, 2016 at 10:27 AM, David Calavera <notifications@github.com>
wrote:

> all [image: :green_heart:] [image: :exclamation:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/engine-api/pull/125#issuecomment-191360138>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by vdemeester** [comment]
LGTM :heart_eyes_cat: (it gives me some idea for libcompose :smile:)

**Pull request merged**
