### PR TITLE
Added network max bandwidth to host config

### PR DESCRIPTION
**Pull request by darrenstahlmsft**
Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by jhowardmsft** [comment]
Hold fire David :) I asked Darren to switch round the ordering of the names to be consistent with everything else which has the device class first

**Comment by darrenstahlmsft** [comment]
Updated. I'll rename the IO stuff in another PR

**Comment by jhowardmsft** [comment]
LGTM :+1:

**Comment by calavera** [comment]
needs rebase :stuck_out_tongue:

**Comment by darrenstahlmsft** [comment]
Darn whitespace. Rebased.

**Comment by darrenstahlmsft** [comment]
CI failing seems to be infra break

**Comment by darrenstahlmsft** [comment]
@calavera Rebased and name changed. PTAL

**Comment by jhowardmsft** [comment]
Still LGTM

**Pull request merged**
