### PR TITLE
Add list of failed task on service inspect

### PR DESCRIPTION
**Pull request by vieux**
ping @aluzzardi @icecrime @stevvooe @tiborvass @dnephin

### CODE REVIEW

**Comment by vdemeester** [comment]
I think related `docker/docker` issue is https://github.com/docker/docker/issues/23706 (and https://github.com/docker/docker/issues/23811) 👼

LGTM 🐳

**Comment by stevvooe** [comment]
👎 If we are going to depart from the swarmkit model, we need to have different type. There is already a task endpoint to get failed tasks. This is the wrong approach.

**Comment by vieux** [comment]
@aluzzardi @icecrime @stevvooe @tiborvass @dnephin how about this ?

**Comment by stevvooe** [comment]
This data is already available through the tasks API. Why have two ways to get it?

It also reenforces the model that services have failures, when it is tasks that have failures.

I really think we need to have `docker service ps` cover this use case.

**Comment by dnephin** [comment]
LGTM

I understand from an object modelling perspective it is not the nicest solution, but for UX `service inspect` is the most natural place to find these errors. 

Either we need to break the convention of `inspect` returning a single API object, or we need this change. It sounds like others prefer this option.

**Comment by stevvooe** [comment]
> I understand from an object modelling perspective it is not the nicest solution, but for UX service inspect is the most natural place to find these errors.

Other than the simple fact that services don't have errors and here we are, teaching users that services have errors.

Let's have a command that displays errors.

**Comment by thaJeztah** [comment]
@stevvooe But a service can have an error in its definition, causing the tasks to fail.
What would be the workflow (from a user-perspective) if I create or update a service, and I see that my replicas stick at 0? What steps should I take to find the error?

(not trolling, just curious how that would work if we take the "correct" model)

**Comment by stevvooe** [comment]
@thaJeztah A service of that nature has a definition such that tasks created for that service result in errors. The issue here is that a misconfiguration may only be temporary. One example is that an image may not exist or be available at service creation time, but may be available later.

We say that such a service cannot "converge".

The appropriate troubleshooting methodology would be as follows:

1. Observe through UI that the service is non-converging (we could report using heuristics at the client or in orchestrator).
2. Investigate cause of task failures.

In `swarmkit`, this is very natural, since the concept of `inspect` is more of a status. Unfortunately, `docker inspect` isn't assembled with multiple API calls and default output isn't very usable, since it is JSON.

We can see the design mistake when we look at `swarmctl service inspect`:

```
$ bin/swarmctl service inspect echo
ID                : 3nb5zdmfrdv5g61zyfttxp8nh
Name              : echo
Replicas          : 1/1
Template
 Container
  Image           : alpine
  Command         : "sleep 1000"

Task ID                      Service    Slot    Image     Desired State    Last State                Node
-------                      -------    ----    -----     -------------    ----------                ----
bqa6jhjodm9rsv6onyhlj2rwd    echo       1       alpine    RUNNING          RUNNING 14 seconds ago    moby
```

If we update this to the wrong image:

```
$ bin/swarmctl service update --image wrongimage echo
$ bin/swarmctl service inspect echo
ID                : 3nb5zdmfrdv5g61zyfttxp8nh
Name              : echo
Replicas          : 0/1
Template
 Container
  Image           : wrongimage
  Command         : "sleep 1000"

Task ID                      Service    Slot    Image         Desired State    Last State                Node
-------                      -------    ----    -----         -------------    ----------                ----
abxcfkjrp6x9jno1hpyq7d3zm    echo       1       wrongimage    ACCEPTED         ACCEPTED 3 seconds ago    moby
```

We'll actually start seeing this flap between rejected and pre-starting states. One can drill down by inspecting tasks and see the error history, but we could show that information here, as well.

The solution here is a user-friendly command that is an assembly of API calls. I propose `docker service status`. This will let us experiment with the proper UX and not introduce hasty, incorrect changes into the API.

**Comment by icecrime** [comment]
LGTM.

**Comment by vieux** [comment]
@aluzzardi found another way to display errors in a meaningful way without changing the API. I'm closing this one.

**Pull request closed without merging**
