### PR TITLE
Keep Runtime from HostConfig capitalized when stored in json format

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
@mlaventure build failing because of the removed import 😇

**Comment by mlaventure** [comment]
@vdemeester ah thanks. I shouldn't trust govendor it seems. It thought it wasn't needed anymore :)

**Comment by cpuguy83** [comment]
LGTM

**Comment by thaJeztah** [comment]
LGTM, dont forget to update the docs when vendoring in docker/docker

**Pull request merged**
