### PR TITLE
Remove /json from API URLs

### PR DESCRIPTION
**Pull request by bfirsh**
See https://github.com/docker/docker/pull/23219

### CODE REVIEW

**Comment by calavera** [comment]
LGTM

**Comment by bfirsh** [comment]
FWIW this has a hard dependency on https://github.com/docker/docker/pull/23219, and that has stalled on a design decision.

**Comment by vdemeester** [comment]
Moving to code-review as docker/docker#23219 is in code-review

**Comment by vdemeester** [comment]
LGTM 🐹

**Comment by calavera** [comment]
still LGTM

**Comment by tamird** [comment]
So...this makes this library not work with older docker versions? For example, the latest version offered by CircleCI is 1.10.

**Comment by vdemeester** [comment]
@tamird arf, yeah that is pretty bad :sweat: 
I'll revert this for now and we'll find a better way to handle it

**Comment by tamird** [comment]
Tim BL had it right all the way back in 1998 https://www.w3.org/Provider/Style/URI.html

**Comment by vdemeester** [comment]
@tamird the old URL won't change (probably for the next… 5 years or eternity) but the client code might… although we didn't do right… Sorry about that :sweat:

**Comment by tamird** [comment]
This client code should also not change until all docker versions that don't support these URLs are EOL'd.

Making this change now is breaking compatibility for no benefit whatsoever, especially given the state of dependency management in Go.

**Comment by vdemeester** [comment]
@tamird see https://github.com/docker/engine-api/pull/263 :bow:

**Comment by tamird** [comment]
👍  thanks

**Comment by bfirsh** [comment]
My bad. I should have closed this while there was still a design decision in https://github.com/docker/docker/pull/23219.

I wonder if we should open the discussion about how to version engine-api. People should presumably be locking to API versions somehow rather than using master. (See also #260.)

**Comment by bfirsh** [comment]
Ah, nevermind, I see there is `cli.version`, so I should have used that in this PR to check what URL to make the request to.

Perhaps we should set the default version to the current stable version of Docker so people using engine-api off master don't get broken by default.

**Comment by vdemeester** [comment]
> Perhaps we should set the default version to the current stable version of Docker so people using engine-api off master don't get broken by default.

That's a good idea :angel:

**Comment by bfirsh** [comment]
@vdemeester I suppose you have to explicitly pass a blank string to `client.NewClient` if you don't want to set a version, so I guess that's pretty much saying "I expect this to break". I'll add a warning to the godoc that you really should be specifying a version.

It's different for `NewEnvClient` though: #264

**Pull request merged**
