### PR TITLE
Removing dead code duplicated in docker/docker

### PR DESCRIPTION
**Pull request by darrenstahlmsft**
As far as I can tell, these functions are duplicated in docker/docker and the docker/docker version is used in all cases. I can submit a parallel PR to docker/docker to confirm that CI passes if needed, but it builds and runs fine locally with these changes.

Signed-off-by: Darren Stahl <darst@microsoft.com>

### CODE REVIEW

**Comment by MHBauer** [comment]
I concur it is not used. I wonder if the usage in `runconfig` will be moving here with the server side or not. It is duplicate code, and if it comes back so be it.

**Comment by msabansal** [comment]
There is another PR pending https://github.com/docker/engine-api/pull/88/ which is required for windows libnetwork integration. NetworkName will be required once Windows libnetwork integration happens(refer https://github.com/docker/docker/pull/20478).

**Comment by darrenstahlmsft** [comment]
Updated to not remove NetworkName

**Comment by calavera** [comment]
LGTM but it needs a rebase.

**Comment by calavera** [comment]
:fire: dead code :fire: :exclamation:

**Pull request merged**
