### PR TITLE
Fix TLS configuration for response hijacking.

### PR DESCRIPTION
**Pull request by calavera**
https://github.com/docker/docker/issues/19280

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by calavera** [comment]
the silliest :pensive:

**Comment by calavera** [comment]
I've also attached the changelog here to merge all together.

**Comment by thaJeztah** [comment]
ping @MHBauer @dongluochen :smile:

**Comment by tiborvass** [comment]
LGTM

**Comment by cpuguy83** [comment]
LGTM, testing with engine and it fixes the issue. We should not flag this as fixing it since it won't really be fixed until this is vendored in.

**Comment by calavera** [comment]
agreed, I've removed the label

**Pull request merged**
