### PR TITLE
Add ExternalCAs to swarm spec

### PR DESCRIPTION
**Pull request by tonistiigi**
New flag added in swarmkit.

ping @aaronlehmann

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by aaronlehmann** [comment]
This format is from https://github.com/docker/swarmkit/pull/1101, which hasn't been merged yet. This PR looks good to me but it needs to wait for https://github.com/docker/swarmkit/pull/1101 to be finalized and merged.

**Comment by jlhawn** [comment]
Now that docker/swarmkit#1101 is merged, is there anything that needs to be changed here?

**Comment by aaronlehmann** [comment]
LGTM

**Comment by tiborvass** [comment]
LGTM

**Pull request merged**
