### PR TITLE
Adding UpdateClientVersion to APIClient interface

### PR DESCRIPTION
**Pull request by nishanttotla**
This part was missed in #185

Signed-off-by: Nishant Totla <nishanttotla@gmail.com>

### CODE REVIEW

**Comment by nishanttotla** [comment]
Ping @dongluochen @vdemeester @duglin

**Comment by vieux** [comment]
LGTM

**Comment by dongluochen** [comment]
LGTM

**Comment by duglin** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM 🐼

**Pull request merged**
