### PR TITLE
Support '--address-space' option to 'network create' options

### PR DESCRIPTION
**Pull request by vikaschoudhary16**
Related to https://github.com/docker/docker/pull/23150
Signed-off-by: vikaschoudhary16 <choudharyvikas16@gmail.com>

### CODE REVIEW

**Comment by vikaschoudhary16** [comment]
Cc @vdemeester  @mavenugo @aboch @mrjana @icecrime

**Comment by calavera** [comment]
LGTM

**Comment by mrjana** [comment]
Not LGTM. Please see my comment: https://github.com/docker/docker/pull/23150#issuecomment-237911402

**Comment by thaJeztah** [comment]
Closing per https://github.com/docker/docker/pull/23150#issuecomment-237911402

**Pull request closed without merging**
