### PR TITLE
Replace secrets with join tokens

### PR DESCRIPTION
**Pull request by aaronlehmann**
Needed for docker/docker#24823.

This changes datastructures in accordance with the upstream swarmkit
changes. It also adds flags to SwarmUpdate to allow token rotation.

### CODE REVIEW

**Comment by tonistiigi** [comment]
LGTM

**Comment by vieux** [comment]
LGTM

**Comment by vieux** [comment]
ping @diogomonica

**Comment by diogomonica** [comment]
LGTM

**Pull request merged**
