### PR TITLE
Add experimental interface for Checkpoint/Restore.

### PR DESCRIPTION
**Pull request by boucher**
The interface is a prerequisite for C/R support in the docker engine.

Signed-off-by: Ross Boucher <rboucher@gmail.com>

### CODE REVIEW

**Comment by boucher** [comment]
The tests pass, but I'm fairly sure they're only running the non experimental build. Not sure if you want to add explicit tests/build support in here for experimental mode, or just let those tests be handled at the Docker level.

**Comment by vdemeester** [comment]
@boucher I think we might want to add tests for experimental mode at some point, but I don't think this is the scope of this PR :stuck_out_tongue:

**Comment by boucher** [comment]
Great :)

**Comment by calavera** [comment]
it would be good if you could add a new Make target to run the tests with the experimental flag on in this PR, we can run it in travis with the normal suite. At least, we'd be certain that this compiles :)

**Comment by boucher** [comment]
@calavera pardon my Go newness. Is something like this in the Makefile what I'm looking for?

    test_experimental:
        go test -tags="test experimental" ./...

**Comment by estesp** [comment]
This looks good based on the fact it looks like a clean migration of the experimental API side of C/R to `engine-api`.  If we're fine with it, it would be great to get this in so we can re-vendor and get the rest of the C/R capability into `docker/docker`.

**Comment by boucher** [comment]
@crosbymichael I'm closing this PR as well, based on our discussion.

**Comment by crosbymichael** [comment]
@boucher ok, thanks!

**Pull request closed without merging**
