### PR TITLE
Use Sockets.ConfigureTransport to remove duplicated code.

### PR DESCRIPTION
**Pull request by calavera**
Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM :heart_eyes_cat:

**Comment by dongluochen** [comment]
LGTM

**Comment by runcom** [comment]
LGTM :)

**Comment by calavera** [comment]
Travis is having issues. This passes tests locally:

```
➜  engine-api git:(use_connections_sockets) make test
go test -tags=test ./...
?   	github.com/docker/engine-api	[no test files]
ok  	github.com/docker/engine-api/client	0.011s
?   	github.com/docker/engine-api/client/transport	[no test files]
?   	github.com/docker/engine-api/client/transport/cancellable	[no test files]
?   	github.com/docker/engine-api/types	[no test files]
?   	github.com/docker/engine-api/types/blkiodev	[no test files]
?   	github.com/docker/engine-api/types/container	[no test files]
?   	github.com/docker/engine-api/types/events	[no test files]
ok  	github.com/docker/engine-api/types/filters	0.005s
?   	github.com/docker/engine-api/types/network	[no test files]
?   	github.com/docker/engine-api/types/registry	[no test files]
ok  	github.com/docker/engine-api/types/strslice	0.005s
ok  	github.com/docker/engine-api/types/time	0.026s
?   	github.com/docker/engine-api/types/versions/v1p19	[no test files]
?   	github.com/docker/engine-api/types/versions/v1p20	[no test files]
➜  engine-api git:(use_connections_sockets)
```

Going to merge to move the vendoring forward.

**Pull request merged**
