### PR TITLE
Remove some dead code.

### PR DESCRIPTION
**Pull request by vdemeester**
convertKVStringsToMap is not use anywhere :)

/cc @calavera @MHBauer @stevvooe @LK4D4 @runcom @thaJeztah 

🐭

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by runcom** [comment]
LGTM not sure what's wrong with win CI

**Comment by LK4D4** [comment]
LGTM

**Comment by vdemeester** [comment]
@runcom it's on its way to be fixed (it's the checkout of `docker/distribution` that fails under windows (and thus on `appveyor`). There is a PR in distribution to fix that :wink:

**Pull request merged**
