### PR TITLE
Windows: Isolation word fix

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

Partly fixes https://github.com/docker/docker/issues/18077. I need this merged into engine-api before I can submit a PR to revendor and patch up the docker engine to match.

### CODE REVIEW

**Comment by calavera** [comment]
what do you think about `IsolationProvider`? it sounds better to me than `Technology`, tbh. But I'm okay with this changes if others like it better.

**Comment by LK4D4** [comment]
I think just `Isolation` sounds better. And it maps to flag name in docker.

**Comment by jhowardmsft** [comment]
I agree with @LK4D4 having thought about it. Updated.

**Comment by LK4D4** [comment]
LGTM

**Comment by dongluochen** [comment]
LGTM

**Comment by jhowardmsft** [comment]
Can we merge this so I can finish the fix in docker/docker? Thanks!

**Comment by calavera** [comment]
Merged, thanks!

**Pull request merged**
