### PR TITLE
Add unit tests for containerInspect

### PR DESCRIPTION
**Pull request by vdemeester**
Wrote a unit test for `ContainerInspect` 🐨 based on the current one (`ContainerStart`).

I was wondering if I should split it into 3 tests or not (my heads tells me it should be 3 unit tests, my finger were lazy :sweat_smile:).

/cc @calavera 

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by MHBauer** [comment]
Yea they should be separate, but then you have to have three mocks. I don't want to encourage dumping a bunch of stuff inside one test however. Your choice.

**Comment by calavera** [comment]
> my heads tells me it should be 3 unit tests, my finger were lazy

please, follow the advice your several head**s** tell you

**Comment by vdemeester** [comment]
@calavera @MHBauer updated with several tests (my head**s** are happier :sweat_smile:).

**Comment by MHBauer** [comment]
That's what I'm talking about. I like it like that. Inlined and everything.

LGTM.

**Comment by calavera** [comment]
LGTM

**Pull request merged**
