### PR TITLE
Add CredentialSpec

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

Adds CredentialSpec to support https://github.com/docker/docker/pull/23389

### CODE REVIEW

**Comment by jhowardmsft** [comment]
ping @crosbymichael - Any chance you can look at this? The docker/docker PR is held behind it. Thx.

**Comment by MHBauer** [comment]
I don't mind LGTM'ing this, as it's clean, but I'd like to make sure that docker/docker#23389 is definitely going in first.

**Comment by jhowardmsft** [comment]
ping @crosbymichael. Can we please move this forward now? Thanks.

**Comment by jhowardmsft** [comment]
Closing now engine-api is back in docker as of 9/7/16.

**Pull request closed without merging**
