### PR TITLE
Add unit tests for ImageCreate

### PR DESCRIPTION
**Pull request by vdemeester**
And it's time for `ImageCreate` 🐼.

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by duglin** [comment]
let's add some tests to make sure that the URL and query params generated by the CLI code are correct

**Comment by calavera** [comment]
> let's add some tests to make sure that the URL and query params generated by the CLI code are correct

@duglin please, go for it.

This PR LGTM as a test case for ImageCreate.

**Comment by vdemeester** [comment]
This PR alreday kinda does that (in a simple naive way :wink:)

**Comment by LK4D4** [comment]
LGTM

**Pull request merged**
