### PR TITLE
Add unit tests for ImagePull

### PR DESCRIPTION
**Pull request by vdemeester**
It has been a while… Here is some unit tests for `ImagePull` 🐙.

It also updates `ImagePull` to not panic if no `PrivilegeFunc` are passed in `ImagePullOptions`.

/cc @calavera @stevvooe @MHBauer

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by LK4D4** [comment]
LGTM

**Comment by thaJeztah** [comment]
ping @aaronlehmann PTAL

**Comment by stevvooe** [comment]
LGTM

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
