### PR TITLE
client: only return ErrConnectionFailed on fatal network errors

### LINKED ISSUE #347: Go 1.7: context.DeadlineExceeded gets returned as ErrConnectionFailed
Well, this was surprising.

In Go 1.7, the "golang.org/x/net/context" package is implemented in terms of the standard library's "context" package.

In particular, here is the definition of [`context.DeadlineExceeded`](https://github.com/golang/net/blob/afc22ee/context/go17.go#L24). Let's follow that thread to the standard library's [`context.DeadlineExceeded`](https://github.com/golang/go/blob/e4dc7f1/src/context/context.go#L158). Note that this error is a custom type, unlike [`context.DeadlineExceeded` pre-1.7](https://github.com/golang/net/blob/afc22ee/context/pre_go17.go#L56).

Now, let's take a quick look at [how engine-api determines when to return `ErrConnectionFailed`](https://github.com/docker/engine-api/blob/5140421/client/request.go#L108:L110) - it uses [`isTimeout`](https://github.com/docker/engine-api/blob/5140421/client/request.go#L206).

Have you guessed it yet? Yep, the standard library's [`deadlineExceeded` implements `Timeout()`](https://github.com/golang/go/blob/e4dc7f1/src/context/context.go#L164), causing engine-api to report "is docker running?" when really the provided context timed out.

This should probably be fixed before the 1.7 release to save others the 3 or so hours I spent debugging this.

### PR DESCRIPTION
**Pull request by tamird**
Fixes #347.

### CODE REVIEW

**Comment by dnephin** [comment]
LGTM

**Comment by tamird** [comment]
Is this waiting on something?

**Comment by tamird** [comment]
@thaJeztah @calavera can you guys take a look? You appear to be the main contributors to this file.

**Comment by vdemeester** [comment]
LGTM 🐸

**Pull request merged**
