### PR TITLE
add 'force' parameter to docker plugin rm to remove an active plugin

### PR DESCRIPTION
**Pull request by vieux**
ping @anusha-ragunathan @tiborvass

### CODE REVIEW

**Comment by anusha-ragunathan** [comment]
LGTM

**Comment by vdemeester** [comment]
@vieux @anusha-ragunathan is there a related PR on `docker/docker` for that ?

**Comment by anusha-ragunathan** [comment]
@vdemeester : I think @vieux is doing this in reverse order. i.e engine-api PR first. vendor it in. then make docker/docker PR. He can confirm that.

**Comment by vieux** [comment]
@anusha-ragunathan is right, sorry I wasn't aware I should do it the other way. I'm going to open the docker/docker PR and link it here

**Comment by vdemeester** [comment]
@vieux cool, thanks 😝
LGTM 🐺

**Comment by thaJeztah** [comment]
LGTM

**Pull request merged**
