### PR TITLE
Change Networks to NetworksStats for container stats

### PR DESCRIPTION
**Pull request by wenchma**
Related to docker/docker#20596

Signed-off-by: wenchma <wenchma@cn.ibm.com>

### CODE REVIEW

**Comment by calavera** [comment]
I rather not do this. It's a breaking change in the api that we'll need to support as backwards compatible.

**Comment by thaJeztah** [comment]
Not convinced either at this point; sure it's slightly nicer, but not sure it's worth the hassle

**Comment by wenchma** [comment]
@calavera @thaJeztah  understanding,  if it's like that :

    Networks map[string]NetworkStats `json:"networks_stats,omitempty"`

just update the json output, is it accepted ?

**Comment by calavera** [comment]
No. Calls to old API versions still need to keep the old field name, to be backwards compatible. That means that you have to fork the stats field by API version only to call the same field `networks_stats` for newer versions and `networks` for older versions. I think adding this extra logic is not worth it.

**Comment by calavera** [comment]
I see the issue is closed already. I'm closing this PR too. Thanks a lot for your clear description in the issue.

**Pull request closed without merging**
