### PR TITLE
Adding link (local alias) config in endpointsettings

### PR DESCRIPTION
**Pull request by mavenugo**
Adding the alias fields in engine-api for the upcoming local alias feature (via link)

Signed-off-by: Madhu Venugopal <madhu@docker.com>

### CODE REVIEW

**Comment by mavenugo** [comment]
@calavera I decided to split the PR between local and global alias in engine-api to reflect the reality as discussed in the maintainers meeting.

**Comment by calavera** [comment]
LGTM

**Comment by mavenugo** [comment]
@calavera am waiting on docker/docker#19198 to be merged before pushing the docker side changes for the alias functionality as discussed. I hope we can get this in soon so that we can avoid temporary vendor-in changes.

**Comment by icecrime** [comment]
LGTM

**Pull request merged**
