### PR TITLE
Homogenize file naming

### PR DESCRIPTION
**Pull request by vdemeester**
> Update file names according to their types…
> … to follow the actual naming pattern. 🐙

This was just bothering me that some files were `container_….go` and other `….go`. 🐠

🐸

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by duglin** [comment]
LGTM 
If it makes you happy :-) 
Just wondering, why not the other ones too, like exec.go, resize.go,etc... ?

**Comment by vdemeester** [comment]
@duglin because I forgot to commit them :sweat: Updating..

**Comment by duglin** [comment]
@vdemeester thanks - still LGTM

**Comment by MHBauer** [comment]
LGTM.

**Comment by calavera** [comment]
Yes, thank you!

**Pull request merged**
