### PR TITLE
Add cgroupDriver to Info

### PR DESCRIPTION
**Pull request by hqhq**
Part of https://github.com/docker/docker/issues/19539

Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Given that there's now work being done on unit-tests; do we need an (updated) test for this change?

/cc @vdemeester

**Comment by vdemeester** [comment]
@thaJeztah The test for `info` is simple and do not check the `Info` field/struct for now so I think no need for update on unit-tests for now :wink:.

**Comment by hqhq** [comment]
ping @calavera @dongluochen @MHBauer

**Comment by thaJeztah** [comment]
LGTM

ping @calavera ptal

**Comment by calavera** [comment]
LGTM

**Pull request merged**
