### PR TITLE
Display `internal` flag on `network inspect`

### PR DESCRIPTION
**Pull request by chenchun**
Signed-off-by: ramichen <ramichen@tencent.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Guess this will be related to https://github.com/docker/docker/pull/19276, but for inspect?

**Comment by chenchun** [comment]
Yes, that's right.

**Comment by thaJeztah** [comment]
LGTM (not a maintainer here)

**Comment by calavera** [comment]
LGTM

**Comment by dongluochen** [comment]
LGTM

**Pull request merged**
