### PR TITLE
Added missing omitempty JSON tag

### LINKED ISSUE #25: does it make sense to omitempty json attributes?
I was just wondering it was possible to have some consistence since some attributes have "omitempty" and others doesn't. For example: https://github.com/docker/engine-api/blob/master/types/types.go#L296
Are there any cons in using the "omitempty" tag?

### PR DESCRIPTION
**Pull request by aanm**
Fixes #25 

Signed-off-by: André Martins <aanm90@gmail.com>

### CODE REVIEW

**Comment by calavera** [comment]
I don't really know the full repercussions of this change. I'd go for it if we could validate that everything in docker keeps working as expected.

**Comment by aanm** [comment]
@calavera In theory should work, other docker-go libraries do the same. But still, how can we prove that?

**Comment by calavera** [comment]
@aanm vendor this patch into docker/docker, run `make test-integration-cli`. We're good if all tests pass :smile:

**Comment by aanm** [comment]
@calavera So I did that but unfortunately some tests failed:
```
FAIL: docker_api_containers_test.go:51: DockerSuite.TestContainerApiGetJSONNoFieldsOmitted

docker_api_containers_test.go:78:
    c.Fatalf("Field %s is missing and it shouldn't", f)
... Error: Field Ports is missing and it shouldn't
```

I did a little more and there's some discussion about this in https://github.com/docker/docker/pull/13703

ping @duglin @runcom

**Comment by runcom** [comment]
I think it's pretty clear that we did that (in the linked PR) because we needed to maintain backward compatibility and do not drop the field if it was empty (IIRC)

**Comment by aanm** [comment]
@runcom Ah! I was missing that. Somehow the statement "To be fully compatible with 1.18, SizeRw and SizeRootFs need to be omit empty." confused me.

**Comment by runcom** [comment]
I'm not confident about adding all those omitempty(s), we had hassles in docker everytime we added/removed one :) not sure we should go with this PR, ping @calavera

**Comment by aanm** [comment]
@runcom I agree and understand your POV. But still I think it's something that needs to be addressed and the sooner the better. I just can't understand why "default" attributes should be sent. If the tests pass, there's not need to be worried :-)

**Comment by jfrazelle** [comment]
Tests don't test everything I'm pretty confident this would break things

**Comment by cyphar** [comment]
The new content-addressibility stuff is particularly important in this regard: we base the hashes on the metadata -- changing what fields are omitted will cause all of that to change.

**Comment by calavera** [comment]
I'm closing this PR given that a few maintainers have expressed their concerns about it. I think we should play save and don't add this if we don't really need it.

Thank you all for your comments.

**Pull request closed without merging**
