### PR TITLE
Add transport types to send to backends.

### PR DESCRIPTION
**Pull request by calavera**
We need these types for docker/docker#19772.

Signed-off-by: David Calavera <david.calavera@gmail.com>

### CODE REVIEW

**Comment by dongluochen** [comment]
@calavera Want to confirm these are migration, no real data structure change. Is that right?

**Comment by calavera** [comment]
that's correct

**Comment by dongluochen** [comment]
LGTM.

**Comment by vdemeester** [comment]
@calavera what is the rational of putting these in the API if it's only used on the server side ? (I might miss something :stuck_out_tongue_closed_eyes:)

**Comment by MHBauer** [comment]
I'm kind of surprised this is all coming over before the server api stuff. I'll go check on https://github.com/docker/docker/pull/19772.

**Comment by calavera** [comment]
> I'm kind of surprised this is all coming over before the server api stuff. I'll go check on docker/docker#19772.

I'm surprised too, tbh. Just wanted to be practice, but it might not be worth it.

**Pull request closed without merging**
