### PR TITLE
add -f to plugin inspect

### PR DESCRIPTION
**Pull request by vieux**
ping @anusha-ragunathan @tiborvass

### CODE REVIEW

**Comment by vdemeester** [comment]
@vieux build errors
```
client/plugin_inspect_test.go:23: client.PluginInspect undefined (type *Client has no field or method PluginInspect)

client/plugin_inspect_test.go:49: client.PluginInspect undefined (type *Client has no field or method PluginInspect)
```

**Comment by vieux** [comment]
@vdemeester fixed, thanks

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by cpuguy83** [comment]
LGTM

**Pull request merged**
