### PR TITLE
Add LiveRestore field to Info struct

### PR DESCRIPTION
**Pull request by mlaventure**
Signed-off-by: Kenfe-Mickael Laventure <mickael.laventure@gmail.com>

--

Related docker PR: https://github.com/docker/docker/pull/24986

### CODE REVIEW

**Comment by icecrime** [comment]
LGTM (but this struct is going to need some breaking some day :innocent:)

**Comment by vdemeester** [comment]
LGTM 🐯
@icecrime I do agree 😇

**Comment by stevvooe** [comment]
Could we please document this field on the godoc? It is not clear what the actual usage is from the name.

**Comment by mlaventure** [comment]
I'll make a new PR for it.

**Pull request merged**
