### PR TITLE
refactor functions in folder github.com/docker/engine-api/client/

### PR DESCRIPTION
**Pull request by SinghamXiao**
Signed-off-by: yuanxiao <yuan.xiao5@zte.com.cn>

### CODE REVIEW

**Comment by vdemeester** [comment]
Hi @yuanxiaoaini, thanks for the contribution but could you provide more context on the changes (in the description of the PR on the changes).

Concerning `getDockerOS`, could you add a test case for `ImageBuild` that shows why the change is needed.

I'm really not a fan of the other changes. Named return are a pain to deal with and making return explicity is easier to read for a human I feel 👼

**Comment by yuanxiaoaini** [comment]
Thank you for your review.
Actually, Nobody can construct the test that " len(matches) == 1 ",  because of the " matches " returns from " matches := headerRegexp.FindStringSubmatch(serverHeader) " only have two kind of values ( nil or slice which length is 2 ). 
However, I'm really do not think the statement of " if len(matches) > 0 {osType = matches[1]} " is a good programming habits. It is hard for me to understand that when " len(matches) > 0 ", " matches[1] " is used.

**Comment by cpuguy83** [comment]
-1 on the named returns.

**Comment by vdemeester** [comment]
ping @SinghamXiao those changes now needs to be done in docker/docker directly (the `client`'s package)

**Comment by crosbymichael** [comment]
Thanks for this PR.

We have moved the code from this repo back into the main docker/docker repository; if you still wish to make this change you will need to reopen this PR on the main repo.  

You can find the code for the client and types here:

https://github.com/docker/docker/tree/master/api/types
https://github.com/docker/docker/tree/master/client

Sorry for the inconvenience but making this change helps people better contribute and not have the vendor mess going forward when changing the types or client for Docker.  

Sorry about that and feel free to ask if you have any questions.

**Pull request closed without merging**
