### PR TITLE
Add a quiet flag to image load for adding progress bar to load

### PR DESCRIPTION
**Pull request by coolljt0725**
Signed-off-by: Lei Jitang <leijitang@huawei.com>

related to https://github.com/docker/docker/pull/17329

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐰

**Comment by duglin** [comment]
Anyone else finding this separate repo really annoying yet? :-)
Seeing this in isolation (and w/o the normal docker tests), and having to coordinate PRs across two repos, is **not** better than just making this a package under docker/docker.
See https://github.com/docker/docker/pull/19746 for another example.

**Comment by duglin** [comment]
LGTM

but please do not merge until docker/docker#17329 is ready to be merged so we know for sure we want it and everything works ok.

**Comment by dnephin** [comment]
Why would the api need to know about this flag? Can't this quiet be implemented entirely on the client side (by not printing to stdout)? Seems unnecessary to make it part of the interface.

I also just realized that our "api definition" seems to be completely missing query params? If that's correct, that's really unfortunate. A large part of the API is not defined by types at all.

> Anyone else finding this separate repo really annoying

maybe, but I think this shows that it's valuable for catching potential issues like above.

**Comment by duglin** [comment]
REST API users should be able to turn this off too.

**Comment by duglin** [comment]
not sure which issue you're referring to but if its about missing docs then I don't see why a separate repo is needed to expose that.  Everything in this repo could be under a pkg in docker/docker and any specialized testing we have here could become unit tests over there.

Given go's ability to import certain dirs from other repos I see no benefit but lots of pain with this approach.

**Comment by dnephin** [comment]
> REST API users should be able to turn this off too.

Isn't "off" just "don't read bytes from the body of the response" ? Why would you need a flag for that?

> not sure which issue you're referring to 

The issue I raised about the new api param being unnecessary.

> I don't see why a separate repo is needed to expose that.

Definitely not necessary, I just think it makes it easier to review changes to the API. By making it a separate repo the API is a first-class concern.  Mixing in API changes with code changes can sometimes hide problems with the API (or at least make them harder to spot).

**Comment by duglin** [comment]
On Jan 28, 2016, at 12:40 PM, Daniel Nephin <notifications@github.com> wrote:
> 
> REST API users should be able to turn this off too.
> 
> Isn't "off" just "don't read bytes from the body of the response" ? Why would you need a flag for that?
> 
a client may not want the noise at all on their networks.

> not sure which issue you're referring to
> 
> The issue I raised about the new api param being unnecessary.
> 
> I don't see why a separate repo is needed to expose that.
> 
> Definitely not necessary, I just think it makes it easier to review changes to the API. By making it a separate repo the API is a first-class concern. Mixing in API changes with code changes can sometimes hide problems with the API (or at least make them harder to spot).
> 
As of now one, for the most part, one can’t happen w/o the other - meaning we can’t fully test API changes w/o the code behind it to see how it will really look-n-feel.  It might be nice to claim that the API is independent of the engine but the reality is that, as of now, its not and except for trivial bug fixes any change in this repo will most likely requite a corresponding change in the engine code. And that PR coordination is annoying, time consuming and a time waste.

**Comment by duglin** [comment]
no real opinion on the flag name - we appear to do both (use short/letters and use full words) at times.

**Comment by calavera** [comment]
This needs a rebase.

**Comment by coolljt0725** [comment]
rebased

**Comment by calavera** [comment]
LGTM

**Pull request merged**
