### PR TITLE
client: pass `serverResponse` around by value

### PR DESCRIPTION
**Pull request by tamird**
Removes a bunch of impossible and useless nil checks.

Signed-off-by: Tamir Duberstein <tamird@gmail.com>

### CODE REVIEW

**Comment by tamird** [comment]
@thaJeztah @calavera can you guys take a look? You appear to be the main contributors to `client/request.go`.

**Comment by cpuguy83** [comment]
I like it, LGTM.

**Comment by LK4D4** [comment]
@tamird It's sorta against the "rules"(like you're supposed to use pointer if your struct contains pointer). I think that it's impossible to have nil serverResp because it's instantiated at the top of `sendClientRequest`, so you can just remove nil-checks.

**Comment by tamird** [comment]
Why are you supposed to use a pointer if the struct contains a pointer?

**Comment by LK4D4** [comment]
@tamird It's code style and it's easier for GC to track such pointers I think.

**Comment by LK4D4** [comment]
@tamird I thought that escape analysis will put them on heap anyway if they contain pointers, maybe I'm wrong.
I still think that it's better to use smaller diff with same effect, because serverResp never can be nil.

**Comment by tamird** [comment]
@LK4D4 escape analysis will put the thing pointed *to* on the heap, not the thing containing the pointer.

No, it is better to have something which is more type safe (which this is, because it doesn't use a nullable pointer at all).

**Comment by LK4D4** [comment]
@tamird ok, you're right
LGTM

**Pull request merged**
